<?php

require __DIR__ . '/vendor/autoload.php';

use GuzzleHttp\Client;

$baseUrl = 'http://127.0.0.1:8000/api/v1';
$client  = new Client(['http_errors' => false]);

echo "\n=========================================================\n";
echo "       🚀 DocuScan SaaS - Live End-to-End Test          \n";
echo "=========================================================\n\n";

// 1. Login
echo "1️⃣  [POST] /api/v1/auth/login\n";
$res = $client->post("$baseUrl/auth/login", [
    'json' => [
        'email'    => 'owner@docuscan.test',
        'password' => 'password123',
    ],
]);
$body = (string) $res->getBody();
$data = json_decode($body, true);
$token = $data['data']['token'];
$user  = $data['data']['user'];
echo "    ✅ Logged in as: {$user['name']} (Role: {$user['role']})\n";
echo "    🏢 Company: {$user['company']['name']}\n";
echo "    🔑 Token: " . substr($token, 0, 20) . "...\n\n";

$authHeaders = [
    'Authorization' => "Bearer {$token}",
    'Accept'        => 'application/json',
];

// 2. Available Plans
echo "2️⃣  [GET] /api/v1/subscriptions/plans\n";
$res   = $client->get("$baseUrl/subscriptions/plans");
$plans = json_decode((string) $res->getBody(), true)['data'];
foreach ($plans as $p) {
    echo "    📦 [{$p['name']}] \${$p['price_monthly']}/mo | Storage: {$p['max_storage_gb']}GB | Users: {$p['max_users']}\n";
}
echo "\n";

// 3. Folders
echo "3️⃣  [GET] /api/v1/folders\n";
$res     = $client->get("$baseUrl/folders", ['headers' => $authHeaders]);
$folders = json_decode((string) $res->getBody(), true)['data'];
$douaneFolderId = null;
foreach ($folders as $f) {
    echo "    📁 ID: {$f['id']} | {$f['name']} (Color: {$f['color']}, Icon: {$f['icon']})\n";
    if (str_contains($f['name'], 'Douane')) {
        $douaneFolderId = $f['id'];
    }
}
echo "\n";

// 4. Upload Document
echo "4️⃣  [POST] /api/v1/documents (Uploading Scanned Customs Document)...\n";
$samplePdfPath = __DIR__ . '/sample_declaration_douane.pdf';
file_put_contents($samplePdfPath, "%PDF-1.4 sample customs clearance certificate generated by DocuScan scanner engine");

$res = $client->post("$baseUrl/documents", [
    'headers'   => $authHeaders,
    'multipart' => [
        ['name' => 'title', 'contents' => 'Declaration Douane Port Casablanca #2026-A89'],
        ['name' => 'description', 'contents' => 'Customs import clearance certificate for electronics shipment'],
        ['name' => 'folder_id', 'contents' => (string) $douaneFolderId],
        [
            'name'     => 'file',
            'contents' => fopen($samplePdfPath, 'r'),
            'filename' => 'declaration_douane_2026.pdf',
        ],
    ],
]);
$uploadData = json_decode((string) $res->getBody(), true);
$doc = $uploadData['data'];
echo "    ✅ Document Uploaded Successfully!\n";
echo "    📄 ID: {$doc['id']} | Title: {$doc['title']}\n";
echo "    📂 Folder: {$doc['folder']['name']} | Size: {$doc['size_formatted']} | Type: {$doc['file_type']}\n\n";

// 5. Search Documents
echo "5️⃣  [GET] /api/v1/documents/search?q=Casablanca\n";
$res = $client->get("$baseUrl/documents/search?q=Casablanca", ['headers' => $authHeaders]);
$searchResults = json_decode((string) $res->getBody(), true)['data'];
foreach ($searchResults as $item) {
    echo "    🔍 Match found: '{$item['title']}' in folder [{$item['folder']['name']}]\n";
}
echo "\n";

// 6. Download Document Link
echo "6️⃣  [GET] /api/v1/documents/{$doc['id']}/download\n";
$res = $client->get("$baseUrl/documents/{$doc['id']}/download", ['headers' => $authHeaders]);
$downloadData = json_decode((string) $res->getBody(), true);
echo "    🔗 Direct Download URL: {$downloadData['download_url']}\n";
echo "    📎 File Name: {$downloadData['file_name']}\n\n";

// 7. Dashboard Statistics
echo "7️⃣  [GET] /api/v1/company/dashboard\n";
$res  = $client->get("$baseUrl/company/dashboard", ['headers' => $authHeaders]);
$dash = json_decode((string) $res->getBody(), true)['data'];
echo "    📊 Total Documents: {$dash['stats']['total_documents']}\n";
echo "    📁 Total Folders: {$dash['stats']['total_folders']}\n";
echo "    👥 Total Team Members: {$dash['stats']['total_users']}\n";
echo "    💾 Storage: {$dash['storage']['used_bytes']} bytes used ({$dash['storage']['usage_percent']}% of {$dash['storage']['limit_gb']} GB)\n";
echo "    ⭐ Active Plan: {$dash['plan']['name']}\n\n";

// Clean up sample test file
if (file_exists($samplePdfPath)) {
    unlink($samplePdfPath);
}

echo "=========================================================\n";
echo "       🎉 All Live Endpoints Tested & Verified!           \n";
echo "=========================================================\n\n";
